spring:
  application:
    name: notification-service

server:
  port: 3106

# Notification Configuration
notification:
  channels:
    email:
      enabled: true
      smtp:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_USERNAME:}
        password: ${EMAIL_PASSWORD:}
    websocket:
      enabled: true
      endpoint: /ws/notifications
    sms:
      enabled: false

# Logging
logging:
  level:
    com.notification.service: DEBUG
    org.springframework.web: INFO