spring:
  application:
    name: adsb-data-simulator
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
    
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

server:
  port: 8080
  
# ADSB Configuration
adsb:
  gimpo:
    latitude: 37.5583
    longitude: 126.7906
    radius: 50 # km
  simulation:
    interval: 5000 # ms
    aircraft-count: 10
  flightradar24:
    api-url: https://api.flightradar24.com/common/v1/
    enabled: false # Set to true when API key is available

# WebSocket Configuration  
websocket:
  allowed-origins: "*"
  
# Logging
logging:
  level:
    com.adsb.simulator: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG